### ISSUE TITLE
Vegetation Layer Error

### ISSUE THREAD

**Issue by WherezWally** [mholling/nswtopo#26]
In V1.4, the script fails when it attempts to create the vegetation layer because of an invalid parameter. For example using the following nswtopo.cfg file:

```
scale: 50000
contour-interval: 10
name: test
latitudes:
- -35.36
- -35.39
longitudes:
- 149.0925
- 149.1325
include:
- nsw/vegetation-2008-v2
- nsw/topographic
exclude:
- nsw.topographic.cadastre
nsw.vegetation-2008-v2:
  path: C:/Carto/NSWInterimNativeVegetationExtentV2_2008/Data/nswintext08/hdr.adf
  colour:
    woody: lightgreen
    non-woody: white 
```

produces the following output:

```
Calculating map bounds...
Map details:
  name: test
  size: 72mm x 66mm
  scale: 1:50000
  rotation: 0.0 degrees
  extent: 3.6km x 3.3km
Creating: nsw.vegetation-2008-v2, 146x134 @ 25.0 m/px
Invalid Parameter - 146x134
```

At this point the script stops and has to be manually aborted.   The same problem occurs when I try to use Spot5 vegetation data.
